server:
  port: 9001
  
  eureka:
  client:
   register-with-eureka:true
    fetch-registry:true
  
    
  spring:
  application:
    name: FIRSTPROJECT
    
   
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
      instance:
    preferIpAddress: true